import pygame as pg

SCREEN_WIDTH, SCREEN_HEIGHT = 800, 600
SCREEN_MARGIN = 50
SCREEN_MARGIN_LEFT = SCREEN_MARGIN
SCREEN_MARGIN_RIGHT = SCREEN_WIDTH - SCREEN_MARGIN
SCREEN_MARGIN_TOP = SCREEN_MARGIN
SCREEN_MARGIN_BOTTOM = SCREEN_HEIGHT - SCREEN_MARGIN

FPS = 30

NUM_BOIDS = 80
NUM_FLOCKS = 4

FLOCK_COLOURS = {
    0: pg.Color("white"),
    1: pg.Color("red"),
    2: pg.Color("green"),
    3: pg.Color("blue"),
}