SCREEN_WIDTH, SCREEN_HEIGHT = 800, 600
SCREEN_MARGIN = 50
SCREEN_MARGIN_LEFT = SCREEN_MARGIN
SCREEN_MARGIN_RIGHT = SCREEN_WIDTH - SCREEN_MARGIN
SCREEN_MARGIN_TOP = SCREEN_MARGIN
SCREEN_MARGIN_BOTTOM = SCREEN_HEIGHT - SCREEN_MARGIN

FPS = 144

NUM_BOIDS = 100